#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.5.2
# from Racc grammar file "".
#

require 'racc/parser.rb'


module Office
  class PlaceholderGrammar < Racc::Parser

module_eval(<<'...end placeholder_grammar.racc/module_eval...', 'placeholder_grammar.racc', 104)
  def initialize
    super
    @field_path = []
    @keywords = {}
    @functors = {}
  end

  attr_reader :field_path
  attr_accessor :image_extent

  # really these have the same function but different syntaxes so keep them separate
  attr_accessor :keywords
  attr_accessor :functors

  def to_h
    {
      field_path: field_path,
      image_extent: image_extent,
      keywords: keywords,
      functors: functors,
    }
  end

  def yydebug; true end

  def read_tokens(tokens)
    # @yydebug = true
    en = case tokens
    when Array; tokens.each
    when Enumerable; tokens
    end

    define_singleton_method(:next_token) do
      en.next
    rescue StopIteration
      nil
    end
    do_parse
    to_h
  end

  # This method is called when a parse error is found.

  # ERROR_TOKEN_ID is an internal ID of token which caused error. You can get
  # string representation of this ID by calling #token_to_str.

  # ERROR_VALUE is a value of error token.

  # value_stack is a stack of symbol values. DO NOT MODIFY this object.

  # This method raises ParseError by default.

  # If this method returns, parsers enter “error recovering mode”.
  def on_error(error_token_id, error_value, value_stack)
    str = token_to_str error_token_id
    puts "error at #{error_value} with #{value_stack.inspect}"
    # binding.pry unless $dont
    super
  end
...end placeholder_grammar.racc/module_eval...
##### State transition tables begin ###

racc_action_table = [
    39,    47,    45,    46,     2,    66,    48,    67,    41,    42,
    39,    47,    45,    46,    34,     3,    48,     4,    41,    42,
    43,    44,    22,    21,    26,    27,    39,    47,    45,    46,
    43,    44,    48,     5,    41,    42,    29,    30,    22,    21,
    22,    55,    29,    30,     9,    10,    43,    44,    11,    12,
    13,    14,     9,    24,    25,    31,    51,    56,    57,    58,
    59,    60,    61,    62,    63,    64,    65 ]

racc_action_check = [
    26,    26,    26,    26,     0,    59,    26,    59,    26,    26,
    27,    27,    27,    27,    26,     1,    27,     2,    27,    27,
    26,    26,    11,    11,    21,    21,    61,    61,    61,    61,
    27,    27,    61,     3,    61,    61,    22,    22,    25,    25,
    34,    34,    39,    39,     4,     6,    61,    61,     7,     8,
     9,    10,    12,    13,    16,    24,    28,    43,    44,    45,
    47,    49,    50,    52,    56,    57,    58 ]

racc_action_pointer = [
    -8,    15,     5,    33,    41,   nil,    32,    34,    34,    34,
    38,    20,    49,    51,   nil,   nil,    36,   nil,   nil,   nil,
   nil,     5,    12,   nil,    38,    36,    -2,     8,    54,   nil,
   nil,   nil,   nil,   nil,    38,   nil,   nil,   nil,   nil,    18,
   nil,   nil,   nil,    51,    52,    53,   nil,    41,   nil,    40,
    44,   nil,    46,   nil,   nil,   nil,    42,    42,    62,     2,
   nil,    24,   nil,   nil,   nil,   nil,   nil,   nil,   nil ]

racc_action_default = [
   -41,   -41,   -41,   -41,    -2,    69,   -41,    -4,    -6,    -8,
   -41,   -41,   -41,   -41,    -1,    -3,   -10,   -11,   -12,   -13,
   -14,   -21,   -41,    -5,   -41,   -41,   -41,   -41,   -41,   -36,
   -37,    -7,    -9,   -15,   -41,   -17,   -24,   -25,   -26,   -27,
   -28,   -29,   -30,   -41,   -41,   -41,   -34,   -41,   -40,   -41,
   -23,   -35,   -41,   -18,   -19,   -21,   -41,   -41,   -41,   -41,
   -20,   -41,   -16,   -31,   -32,   -33,   -38,   -39,   -22 ]

racc_goto_table = [
    49,    17,    15,     7,     1,     6,    54,    33,    52,    35,
   nil,    23,   nil,   nil,   nil,    17,    32,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    53,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    68 ]

racc_goto_check = [
    14,     7,     4,     3,     1,     2,    10,    11,    12,    13,
   nil,     3,   nil,   nil,   nil,     7,     4,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,     7,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    14 ]

racc_goto_pointer = [
   nil,     4,     1,    -1,    -9,   nil,   nil,   -10,   nil,   nil,
   -28,   -19,   -26,   -17,   -27,   nil,   nil,   nil,   nil ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,     8,    16,    38,    18,    19,
    20,   nil,   nil,    50,   nil,    36,    37,    40,    28 ]

racc_reduce_table = [
  0, 0, :racc_error,
  5, 27, :_reduce_none,
  0, 28, :_reduce_none,
  3, 28, :_reduce_none,
  1, 28, :_reduce_none,
  3, 29, :_reduce_none,
  1, 29, :_reduce_none,
  4, 31, :_reduce_7,
  1, 31, :_reduce_8,
  3, 30, :_reduce_none,
  1, 30, :_reduce_none,
  1, 32, :_reduce_11,
  1, 32, :_reduce_none,
  1, 32, :_reduce_none,
  1, 32, :_reduce_none,
  3, 34, :_reduce_15,
  3, 37, :_reduce_16,
  1, 37, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  4, 35, :_reduce_20,
  1, 36, :_reduce_21,
  3, 40, :_reduce_22,
  1, 40, :_reduce_none,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 39, :_reduce_27,
  1, 39, :_reduce_none,
  1, 42, :_reduce_29,
  1, 42, :_reduce_30,
  3, 41, :_reduce_31,
  3, 41, :_reduce_32,
  3, 41, :_reduce_33,
  1, 41, :_reduce_none,
  3, 33, :_reduce_35,
  1, 44, :_reduce_none,
  1, 44, :_reduce_none,
  3, 43, :_reduce_38,
  3, 43, :_reduce_39,
  1, 43, :_reduce_none ]

racc_reduce_n = 41

racc_shift_n = 69

racc_token_table = {
  false => 0,
  :error => 1,
  :NUMBER => 2,
  :IDENTIFIER => 3,
  :LRQUOTE => 4,
  :MAGIC_QUOTED => 5,
  :STRING => 6,
  :BOOLEAN => 7,
  :RANGE => 8,
  :CHAR => 9,
  :false => 10,
  :true => 11,
  "{" => 12,
  "}" => 13,
  "|" => 14,
  "." => 15,
  "[" => 16,
  "]" => 17,
  "," => 18,
  ":" => 19,
  "(" => 20,
  ")" => 21,
  "\"" => 22,
  "'" => 23,
  "X" => 24,
  "x" => 25 }

racc_nt_base = 26

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "NUMBER",
  "IDENTIFIER",
  "LRQUOTE",
  "MAGIC_QUOTED",
  "STRING",
  "BOOLEAN",
  "RANGE",
  "CHAR",
  "false",
  "true",
  "\"{\"",
  "\"}\"",
  "\"|\"",
  "\".\"",
  "\"[\"",
  "\"]\"",
  "\",\"",
  "\":\"",
  "\"(\"",
  "\")\"",
  "\"\\\"\"",
  "\"'\"",
  "\"X\"",
  "\"x\"",
  "$start",
  "cuddled",
  "placeholder",
  "field_path",
  "directives",
  "nstep",
  "directive",
  "extent",
  "keyword",
  "functor",
  "naked",
  "composite_value",
  "array_value",
  "value",
  "values",
  "string",
  "boolean",
  "range",
  "x" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

module_eval(<<'.,.,', 'placeholder_grammar.racc', 42)
  def _reduce_7(val, _values, result)
     self.field_path << val[0]; self.field_path << Integer(val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'placeholder_grammar.racc', 43)
  def _reduce_8(val, _values, result)
     self.field_path << val[0]
    result
  end
.,.,

# reduce 9 omitted

# reduce 10 omitted

module_eval(<<'.,.,', 'placeholder_grammar.racc', 48)
  def _reduce_11(val, _values, result)
    self.image_extent = val[0]
    result
  end
.,.,

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

module_eval(<<'.,.,', 'placeholder_grammar.racc', 54)
  def _reduce_15(val, _values, result)
     self.keywords[val[0].to_sym] = val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'placeholder_grammar.racc', 57)
  def _reduce_16(val, _values, result)
    result = val[1]
    result
  end
.,.,

# reduce 17 omitted

# reduce 18 omitted

# reduce 19 omitted

module_eval(<<'.,.,', 'placeholder_grammar.racc', 63)
  def _reduce_20(val, _values, result)
     self.functors[val[0].to_sym] = val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'placeholder_grammar.racc', 65)
  def _reduce_21(val, _values, result)
     self.keywords[val[0].to_sym] = true
    result
  end
.,.,

module_eval(<<'.,.,', 'placeholder_grammar.racc', 70)
  def _reduce_22(val, _values, result)
    result = [*Array(val[0]), *Array(val[2])]
    result
  end
.,.,

# reduce 23 omitted

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

module_eval(<<'.,.,', 'placeholder_grammar.racc', 74)
  def _reduce_27(val, _values, result)
    result = Integer val[0]
    result
  end
.,.,

# reduce 28 omitted

module_eval(<<'.,.,', 'placeholder_grammar.racc', 78)
  def _reduce_29(val, _values, result)
    result = false
    result
  end
.,.,

module_eval(<<'.,.,', 'placeholder_grammar.racc', 78)
  def _reduce_30(val, _values, result)
    result = true
    result
  end
.,.,

module_eval(<<'.,.,', 'placeholder_grammar.racc', 81)
  def _reduce_31(val, _values, result)
    result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'placeholder_grammar.racc', 82)
  def _reduce_32(val, _values, result)
    result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'placeholder_grammar.racc', 83)
  def _reduce_33(val, _values, result)
    result = val[1]
    result
  end
.,.,

# reduce 34 omitted

module_eval(<<'.,.,', 'placeholder_grammar.racc', 87)
  def _reduce_35(val, _values, result)
     result = {width: val[0], height: val[2]}
    result
  end
.,.,

# reduce 36 omitted

# reduce 37 omitted

module_eval(<<'.,.,', 'placeholder_grammar.racc', 94)
  def _reduce_38(val, _values, result)
    result = "#{val[0]}:#{val[2]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'placeholder_grammar.racc', 95)
  def _reduce_39(val, _values, result)
    result = "#{val[0]}:#{val[2]}"
    result
  end
.,.,

# reduce 40 omitted

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class PlaceholderGrammar
end   # module Office
